### ISSUE TITLE
Search result "invisible"

### ISSUE THREAD

**Issue by ac3nl** [Aemiii91/miyoomini-SearchFilter#2]
After a search i only see 2 lines of results 

When i scroll down, more items magically appear. I am on onion 3.12.3, but have no idea if that is the reason.

**Comment by Aemiii91** [comment]
Unfortunately, this is out of my hands, because it's a side effect of the stock MainUI and how it saves the lists in memory. A quick method for having the entire list appear, is to scroll up at the top and down again (a quick UP, DOWN press).
