### ISSUE TITLE
[bug] version 1.2 F*cked up all my EMU Jason files

### ISSUE THREAD

**Issue by ac3nl** [Aemiii91/miyoomini-SearchFilter#3]
installed filters, and did a refresh rom (single console)
miyoo crashed

after i removed "filters" all me jason's were f*cked up
no linebreaks were in the files, and nothing worked

had to install every single console again

**Comment by Aemiii91** [comment]
It has been fixed in 1.2.1

**Comment by ac3nl** [comment]
Backing up the jason files would make sense, as i have a few custom ones

**Comment by Aemiii91** [comment]
That could be a way to do it, but the *config patch function* is set up to only change the `launch` value (only if it's currently set to `launch.sh`) and add an extra extension to `extlist` if it's not empty. So any customizations should be retained.
